### ISSUE TITLE
Problem with pattern 2

### ISSUE THREAD

**Issue by Roman555** [dmitry-pdp/InstantStore-Dev#13]
1.Log administrator
2.Enter control panel
3.Entern a pattern
4.Create new pattern 
5.If name pattern is empty have error
![default](https://cloud.githubusercontent.com/assets/18558785/14792237/09489acc-0b22-11e6-9765-a79876ab2212.jpg)

**Comment by dmitry-pdp** [comment]
Good catch. Fixed.
