### ISSUE TITLE
log problem 

### ISSUE THREAD

**Issue by Roman555** [dmitry-pdp/InstantStore-Dev#19]
1.Try login how user
2.Wrote incorrect pasword or login 
3.Login how admin sucsess
4.Exit how admin
5.login how user all work 
Fidder install.What me do ?

**Comment by Roman555** [comment]
In studs.by my user login dont work ?

**Comment by dmitry-pdp** [comment]
I don't think it is registered in the database.

**Comment by Roman555** [comment]
What to do ?

**Comment by dmitry-pdp** [comment]
I'll fix it in studs and update this issue.

**Comment by Roman555** [comment]
Cannot log as user 
Wrote incorrect pasword or login

**Comment by dmitry-pdp** [comment]
I reset the password for your account. 
Please try again and let me know if anything.
