### ISSUE TITLE
studs.by bug

### ISSUE THREAD

**Issue by Roman555** [dmitry-pdp/InstantStore-Dev#22]
1.Open site studs.by
2.Direct on link "Система для прокалывания ушей "System 75" фирмы Studex" in the uppert part  menu
Direct on link "Система для прокалывания ушей "System 75" "
2.Click on link "Серги" and see empty catalog.
![problem catalog](https://cloud.githubusercontent.com/assets/18558785/15220944/06ce3f24-1872-11e6-9827-9da51cc00358.png)

**Comment by Roman555** [comment]
I think "Серги" extra submenu

**Comment by dmitry-pdp** [comment]
Not a bug nor program failure.
Site owner didn't fill the data.
