### ISSUE TITLE
Studs.by

### ISSUE THREAD

**Issue by Roman555** [dmitry-pdp/InstantStore-Dev#24]
1.Log as admin
2.Open control panel
3.Open user settings 
4.Changing user currency any diferent from "бел руб"
5.Save settings
6.See a bug
![studs](https://cloud.githubusercontent.com/assets/18558785/15512889/ca1574b2-21ea-11e6-8d13-2a02b3a4c1af.png)

**Comment by dmitry-pdp** [comment]
Does it reproduce on pwatcher.com/instantstore?

**Comment by Roman555** [comment]
No.This a new bug

**Comment by Roman555** [comment]
This happens on the user Potash

**Comment by dmitry-pdp** [comment]
Fixed
