### ISSUE TITLE
studs bug

### ISSUE THREAD

**Issue by Roman555** [dmitry-pdp/InstantStore-Dev#25]
1.Log as admin
2.Open control panel
3.Open user settings 
4.Changing user payment type on "Безналичный расчёт"
5.Save settings
6.See a bug
![studs](https://cloud.githubusercontent.com/assets/18558785/15512981/4220d2e4-21eb-11e6-95e5-a79ff50e960a.png)

**Comment by dmitry-pdp** [comment]
I can't reproduce it. Could you attach fiddler logs?

**Comment by Roman555** [comment]
This happens on the user Поташ

**Comment by dmitry-pdp** [comment]
Fixed.
