### ISSUE TITLE
Проблема с блокировкой пользователя 

### ISSUE THREAD

**Issue by Roman555** [dmitry-pdp/InstantStore-Dev#5]
Заблокировал свой аккаунт.Пришло письмо на mail о блокировке аккаунта.Но заходить под своим аккаунтом я могу.

**Comment by dmitry-pdp** [comment]
Подтверждаю - баг.

**Comment by dmitry-pdp** [comment]
Пофиксил баг. 
Тебе надо сейчас проверить и если действительно стало как надо, то закрывай этот issue.
