### ISSUE TITLE
Problem with price 2

### ISSUE THREAD

**Issue by Roman555** [dmitry-pdp/InstantStore-Dev#6]
1.If currency in RUR problem when i log how user at a choice any link with price show
 Server Error in '/InstantStore' Application 
1.Log in how user
2.Choice any link with price
3.Server Error in '/InstantStore' Application

**Comment by dmitry-pdp** [comment]
Confirmed as a bug.

**Comment by dmitry-pdp** [comment]
The page was crashing due to the fact that there is no conversion rate defined between product's currency and user's currency. 

Fixed: Now if there is no conversion rate available the price is set to zero.
